### ISSUE TITLE
compile help

### ISSUE THREAD

**Issue by baldonazionale** [dtkdt100/Chat-GPT-for-Gmail#1]
hi @dtkdt100 , can you suggest a guide to compile your code and create better or different version of your extension?
thanks!

**Comment by baldonazionale** [comment]
solved, here's the steps:

- install node.js + NPV
- install GIT
- `git clone https://github.com/dtkdt100/Chat-GPT-for-Gmail`
- `npm install`
- `npm run build`

**Comment by dtkdt100** [comment]
Thanks for opening the issue, I added local installation section to the README.md file. 

See https://github.com/dtkdt100/Chat-GPT-for-Gmail/commit/29867c4f7f28c70a6fbc87dce46a705034f0849b
